

struct arvore ddds[67] = {
    {11, "São Paulo (Capital)"},
    {12, "São José dos Campos e região"},
    {13, "Santos e região"},
    {14, "Bauru e região"},
    {15, "Sorocaba e região"},
    {16, "Ribeirão Preto e região"},
    {17, "São José do Rio Preto e região"},
    {18, "Presidente Prudente e região"},
    {19, "Campinas e região"},
    {21, "Rio de Janeiro (capital) e região metropolitana"},
    {22, "Campos dos Goytacazes e região"},
    {24, "Volta Redonda e região"},
    {27, "Vitória e região metropolitana"},
    {28, "Cachoeiro de Itapemirim e região"},
    {31, "Belo Horizonte e região metropolitana"},
    {32, "Juiz de Fora e região"},
    {33, "Governador Valadares e região"},
    {34, "Uberlândia e região"},
    {35, "Poços de Caldas e região"},
    {37, "Divinópolis e região"},
    {38, "Montes Claros e região"},
    {41, "Curitiba e região metropolitana"},
    {42, "Ponta Grossa e região"},
    {43, "Londrina e região"},
    {44, "Maringá e região"},
    {45, "Foz do Iguaçu e região"},
    {46, "Francisco Beltrão e região"},
    {47, "Joinville e região"},
    {48, "Florianópolis e região metropolitana"},
    {49, "Chapecó e região"},
    {51, "Porto Alegre e região metropolitana"},
    {53, "Pelotas e região"},
    {54, "Caxias do Sul e região"},
    {55, "Santa Maria e região"},
    {61, "Brasília e região metropolitana"},
    {62, "Goiânia e região metropolitana"},
    {63, "Palmas e região"},
    {64, "Rio Verde e região"},
    {65, "Cuiabá e região metropolitana"},
    {66, "Rondonópolis e região"},
    {67, "Campo Grande e região metropolitana"},
    {68, "Rio Branco e região"},
    {69, "Porto Velho e região"},
    {71, "Salvador e região metropolitana"},
    {73, "Ilhéus e região"},
    {74, "Juazeiro e região"},
    {75, "Feira de Santana e região"},
    {77, "Barreiras e região"},
    {79, "Aracaju e região metropolitana"},
    {81, "Recife e região metropolitana"},
    {82, "Maceió e região metropolitana"},
    {83, "João Pessoa e região metropolitana"},
    {84, "Natal e região metropolitana"},
    {85, "Fortaleza e região metropolitana"},
    {86, "Teresina e região metropolitana"},
    {87, "Petrolina e região"},
    {88, "Juazeiro do Norte e região"},
    {89, "Picos e região"},
    {91, "Belém e região metropolitana"},
    {92, "Manaus e região metropolitana"},
    {93, "Santarém e região"},
    {94, "Marabá e região"},
    {95, "Boa Vista e região"},
    {96, "Macapá e região metropolitana"},
    {97, "Coari e região"},
    {98, "São Luís e região metropolitana"},
    {99, "Imperatriz e região"},
};

